//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AstronomyDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class APDBEntities : DbContext
    {
        public APDBEntities()
            : base("name=APDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Star> Star { get; set; }
        public virtual DbSet<PictureOfTheDay> PictureOfTheDay { get; set; }
        public virtual DbSet<Asteroid> Asteroid { get; set; }
        public virtual DbSet<AsteroidnNearEarth> AsteroidnNearEarth { get; set; }
    }
}
