//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AstronomyDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Star
    {
        public string Name { get; set; }
        public string ObjectUri { get; set; }
        public string Id { get; set; }
        public string AbsoluteMagnitude { get; set; }
        public string diameterAvrege { get; set; }
        public string IsPotentiallyHazardousAsteroid { get; set; }
        public string Velocity { get; set; }
        public string missDistance { get; set; }
        public string OrbitingBody { get; set; }
        public string IsSentryObject { get; set; }
    }
}
